services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "8025:8025"
      - "1025:1025"

  app:
    image: 'paystubs-api:latest'
    build:
      context: .
    container_name: app
    depends_on:
      mailpit:
        condition: service_healthy
    ports:
      - "8085:8085"
