spring:
  application:
    name: "Paystubs API"

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USER:no-reply@example.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: ${MAIL_AUTH:false}
      mail.smtp.starttls.enable: ${MAIL_STARTTLS:false}

server:
  port: 8085

app:
  auth:
    password: ${APP_PASSWORD:pwd}
    user: ${APP_USER:user}